version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v-code-backend-2
    ports:
      - "3000:3000"
    environment:
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: v-code-db
    restart: always
    environment:
      POSTGRES_USER: code_editor_owner
      POSTGRES_PASSWORD: 
      POSTGRES_DB: code_editor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
